# theme: jekyll-theme-midnight
theme: jekyll-theme-minimal
# theme: minima
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
title: SQL Server HowTo
description: Aide pour opérations administratives, développement et optimisation dans Microsoft SQL Server